
export const dialogDefault = {
    open: false,
    id: 0,
};

export const catalogsName = 'catalogs';

export const DIALOG_PERCAPITA = 'DIALOG_PERCAPITA';
export const DIALOG_CUSTOMER = 'DIALOG_CUSTOMER';

export const OPEN_DIALOG_BENEFICIARY = 'OPEN_DIALOG_BENEFICIARY';
export const CLOSE_DIALOG_BENEFICIARY = 'CLOSE_DIALOG_BENEFICIARY';

export const DIALOG_INPUTPRODUCT = 'DIALOG_INPUTPRODUCT';
export const DIALOG_OUTPUTPRODUCT = 'DIALOG_OUTPUTPRODUCT';
export const DIALOG_PRODUCT = 'DIALOG_PRODUCT';

export const DIALOG_WORKORDER = 'DIALOG_WORKORDER';
export const DIALOG_WORKORDERS = 'DIALOG_WORKORDERS';

export const GET_CATALOGS = 'GET_CATALOGS';
export const DIALOG_TRANSFER = 'DIALOG_TRANSFER';